title: Computer Science
author: Mohammad Atieh
email: matie1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  This blog will disucuss the three main features of 
  computer science in order to further teach people about certain
  aspects of it.
  
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
